server:
  port: 8081
  servlet:
    context-path: /api/market-place

spring:
  application:
    name: Market Place         
  datasource:
    url: jdbc:postgresql://localhost:5432/market_place
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true